name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-sbt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [ 2.11.12, 2.12.18, 2.13.12 ]
    name: Scala ${{matrix.scala}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build and run tests
        run: sbt ++${{matrix.scala}} test
